name: Daily Telegram Motivation

on:
  schedule:
    - cron: '0 1 * * *'     # 6:30 AM IST (cron is in UTC)
    - cron: '30 14 * * *' # 8:00 PM IST
  workflow_dispatch:

jobs:
  send-motivation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
        run: python daily_roast.py
